language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/nosetests openprocurement/schemas/dgf/tests/
after_success:
  - bin/coveralls
